homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation 
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  # Customization file
  customize: !include customize.yaml
  
http:
  ip_ban_enabled: True
  login_attempts_threshold: 5
  api_password: !secret api_password

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Sensors
sensor:
  # Weather prediction
  - platform: yr

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_networkkey
  debug: true
  
ecobee:
  api_key: !secret ecobee_password
  
media_player:
  - platform: denonavr
    host: !secret denonavr_ip
    name: Denon Receiver
    show_all_sources: False
    zones:
      - zone: Zone2
        name: Denon DVR Zone2
  - platform: vizio
    host: 192.168.0.103
    access_token: !secret vizio_authorization_token

device_tracker:
  - platform: bluetooth_tracker
  
zone:
  - name: Work
    latitude: 32.9588
    longitude: -96.8221
    
  - name: Sprouts
    latitude: 32.9769
    longitude: -96.7649
    
abode:
  username: cbuechel3@gmail.com
  password: !secret abode_password
  name: Abode Alarm System
  
tuya:
  username: cbuechel3@gmail.com
  password: !secret tuya_password
  country_code: 1
  
notify:
  - platform: pushbullet
    name: PushBullet
    api_key: !secret pushbullet_password